### ISSUE TITLE
Music Chart Display for Joomla - more Charts?

### ISSUE THREAD

**Issue by skyfly24** [trananhmanh89/mod-ff-music-chart#1]
First of all, thank you for this great module.
- Is it also possible to integrate the charts from https://www.offiziellecharts.de/charts?
- Can a Spotify or similar link also be integrated?
greetings

**Comment by trananhmanh89** [comment]
1. About https://www.offiziellecharts.de/charts, yes. If you hire me, it's gonna faster :D
2. I don't understand what you want to intergrate from Spotify?

**Comment by skyfly24** [comment]
1. I'm unfortunately only private. :-) what should it cost?
2. To listen to the song :-)

**Comment by trananhmanh89** [comment]
1. 10 bucks. Contact me ----
2. My module only shows music chart. You should use spotify embed directly.
